apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kubectl-role
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubectl-service-account
  namespace: default
roleRef:
  kind: Role
  name: kubectl-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name of the cluster role
  name: kubectl-scale-role
rules:
- apiGroups: [""]
  resources: ["deployments/scale"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-scale-binding
subjects:
- kind: ServiceAccount
  name: kubectl-service-account  # Replace with your CronJob's service account name
  namespace: default  # Replace with your CronJob's namespace
roleRef:
  kind: ClusterRole
  name: kubectl-scale-role
  apiGroup: rbac.authorization.k8s.io

