apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1  # Start with 1 replica, it will scale based on HPA
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: hariprasad095/2023mt03165-userservice:latest  # Replace with your Docker image
          ports:
            - containerPort: 5001
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort  # Change this from ClusterIP to NodePort
  ports:
    - port: 80               # Port on the cluster
      targetPort: 5001       # Port your app listens on
      nodePort: 30001        # Optional: you can specify or let Kubernetes auto-assign it
  selector:
    app: user-service
